name: chubby_bubble
version: 0.0.1
repository: https://github.com/hanskokx/chubby_bubble
description: >-
  ChubbyBubble is a toolkit for building beautiful terminal user interfaces,
  which was designed to be extensive and simple to use.
environment:
  sdk: ^3.0.0

dependencies:
  dart_console: ^4.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0

platforms:
  windows:
  linux:
  macos:
