name: chubby_bubble
version: 0.0.1
description: >-
  A toolkit for building beautiful terminal user interfaces.
  ChubbyBubble was designed to be extensive and simple to use. Presently, the
  only available module is the [panel] module. This can be invoked using the
  [ChubbyBubble.panel] constructor.
repository: https://github.com/hanskokx/chubby_bubble
environment:
  sdk: ^3.0.0

dependencies:
  dart_console: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

platforms:
  windows:
  linux:
